name: Check_Branch_Name

on:
  push:
    branches: ["*"]

jobs:   # 👈 REQUIRED
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Branch Name
        run: echo "Branch name:" ${{ github.ref_name }}