name: Branch Name Validation

on:
  push:
    branches: [ "main" ]

  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run a command
        run: echo "mybranch_name is ${{ github.ref_name }}"

  pr-title-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Validate PR title starts with future/
        shell: bash
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"

          echo "Raw PR title: '$PR_TITLE'"

          # normalize (trim spaces + lowercase)
          PR_TITLE_CLEAN=$(echo "$PR_TITLE" | xargs | tr '[:upper:]' '[:lower:]')

          echo "Normalized PR title: '$PR_TITLE_CLEAN'"

          if [[ ! "$PR_TITLE_CLEAN" =~ ^future/ ]]; then
            echo "Invalid PR title"
            echo "PR title must start with 'future/'"
            exit 1
          fi

          echo "PR title is valid"
